# Numpy

In [93]:
import numpy as np

## Ustvarjanje vektorjev

`np.linspace(a, b, n)` vrne vektor `n` ekvidistančnih točk na intervalu `[a,b]`.

In [94]:
x = np.linspace(0, 1, 6)
print(x)

[0.  0.2 0.4 0.6 0.8 1. ]


## Preoblikovane vektorjev

`np.roll(x, shift)` premakne elemente vektorja `x` za `shift` mest. Če je `shift` pozitivno celo število, se premik izvede v desno, če je negativno, se premik izvede v levo.


In [95]:
y = np.roll(x,1)
print(y)

[1.  0.  0.2 0.4 0.6 0.8]


In [96]:
y = np.roll(x, -1)
print(y)

[0.2 0.4 0.6 0.8 1.  0. ]


`np.reshape(x, newshape)` vrne nov `ndarray` elementov `x` oblike `newshape`. Produkt dimenzij `newshape` mora biti enak številu elementov `x`.

In [97]:
x = np.arange(12)
print(x)

[ 0  1  2  3  4  5  6  7  8  9 10 11]


In [98]:
# Preoblikujemo vektor v matriko 
matrika = np.reshape(x, (3,4))
print(matrika)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [99]:
# Preoblikujemo vektor v 3-dimenzionalni array 
tridarray = np.reshape(x, (2,3,2))
print(tridarray)

[[[ 0  1]
  [ 2  3]
  [ 4  5]]

 [[ 6  7]
  [ 8  9]
  [10 11]]]


Elementi se v novo obliko razporedijo po vrsti, prvi po zadnji osi, nato po predzadnji, itd. V primeru matrike je druga os `(axis=1)` vrstica in prva os `(axis=0)` stolpec. V primeru $3$-dimenzionalnega arraya je tretja os `(axis=2)` stolpec, druga os `(axis=1)` vrstica in prva os `(axis=0)` globina.

In [100]:
y = np.reshape(tridarray, 12)
print(y)

[ 0  1  2  3  4  5  6  7  8  9 10 11]


`np.flip(x, axis=None)` obrne vrstni red elementov vzdolž določene osi. Privzeta vrednost `axis=None` obrne elemente vzdolž vseh osi.

In [102]:
print(x)

[ 0  1  2  3  4  5  6  7  8  9 10 11]


In [103]:
y = np.flip(x)
print(y)

[11 10  9  8  7  6  5  4  3  2  1  0]


In [109]:
print(matrika)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [ ]:
# Obrnemo vrsti red po stolpcih
y = np.flip(matrika, axis=0)
print(y)

In [ ]:
# Obrnemo vrstni red po vrsticah
y = np.flip(matrika, axis=1)
print(y)

In [ ]:
# Obrnemo vrstni red po stolpchi in vrsticah
y = np.flip(matrika)
print(y)

[[11 10  9  8]
 [ 7  6  5  4]
 [ 3  2  1  0]]


`np.flip(matrika)` ni enako kot transponiranje `matrika.T`.

In [106]:
y = matrika.T
print(y)

[[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]


## Iskanje elementov

`np.flatnonzero(x)` vrne vektor indeksov vseh neničelnih elementov v `x`. 

Vhod `x` najprej splošči v enodimenzionalni vektor (tako kot `np.reshape(x, newshape)`, kjer je `newshape` enak številu elementov v `x`). Nato vrne vse indekse `i`, kjer `x[i] != 0`.

In [146]:
x = np.array([0, 5, 1, 0, 7, 0])
print(x)

[0 5 1 0 7 0]


In [147]:
y = np.flatnonzero(x)
print(y)

[1 2 4]


In [148]:
matrika = np.reshape(x, (2,3))
print(matrika)

[[0 5 1]
 [0 7 0]]


In [149]:
y = np.flatnonzero(matrika)
print(y)

[1 2 4]


`np.where(condition)` vrne $N-terico$ indeksov, kjer je `condition == True`.

In [150]:
x = np.array([0, 5, 1, 0, 7, 0])
print(x)

[0 5 1 0 7 0]


Za vektorje vrne en vektor indeksov.

In [156]:
# Nadjdemo indekse elementov, ki so večji od 0
indeksi = np.where(x > 0)
print(indeksi)

# Elementi, ki so večji od 0
y = x[indeksi]
print(y)

(array([1, 2, 4], dtype=int64),)
[5 1 7]


Za matriko vrne dvojico indeksov `(vrsice, stolpci)`.

In [157]:
print(matrika)

[[0 5 1]
 [0 7 0]]


In [158]:
indeksi = np.where(matrika > 0)
print(indeksi)

y = matrika[indeksi]
print(y)

(array([0, 0, 1], dtype=int64), array([1, 2, 1], dtype=int64))
[5 1 7]


np.where(condition, t, f) vrne `ndarray` iste oblike kot `condition`, kjer:
* na indeksih kjer je `condition[i] == True`, vrne vrednosti `t`,
* na indeksih kjer je `condition[i] == False`, vrne vrednosti `f`.

In [160]:
x = np.array([0, 5, 1, 0, 7, 0])
print(x)

[0 5 1 0 7 0]


In [161]:
y = np.where(x % 2 == 0, "sodo", "liho")
print(y)

['sodo' 'liho' 'liho' 'sodo' 'liho' 'sodo']


## Kumulativna vsota

`np.cumsum(x, axis=None)` izračuna kumulativno vsoto elementov `x` vzdolž določene osi. Privzeta vrednost `axis=None` izračuna vzdolž vseh osi.

In [166]:
x = np.array([1, 2, 3, 4])
print(x)

[1 2 3 4]


In [169]:
y = np.cumsum(x)
print(y)

[ 1  3  6 10]


In [167]:
matrika = np.array(
    [
        [1,2,3], 
        [4,5,6]
    ]
)
print(matrika)

[[1 2 3]
 [4 5 6]]


In [ ]:
# Kumulativna vsota vzdolž stolpcev
y = np.cumsum(matrika, axis=0)
print(y)

[[1 2 3]
 [5 7 9]]


In [ ]:
# Kumulativna vsota vzdolž vrstic
y = np.cumsum(matrika, axis=1)
print(y)

[[ 1  3  6]
 [ 4  9 15]]


In [174]:
# Kumultivna vsota celotnega niza
y = np.cumsum(matrika)
print(y)

[ 1  3  6 10 15 21]


## Za danes je dobro vedeti

### Ustvarjanje
* `np.linspace(a, b, n)` ustvari vektor `n` ekvidistančnih točk na intervalu `[a,b]`.

### Preoblikovanje
* `np.roll(x, shift)` ciklično premakne elemente za `shift` mest (desno če pozitivno, levo če negativno).
* `np.reshape(x, newshape)` preoblikuje `x` v novo obliko.
* `np.flip(x, axis=None)` obrne vrstni red elementov vzdolž določene osi.

### Osi
* **Matrika** oblike $(m, n)$:
  - `axis=0`: vrstice ($m$ vrstic),
  - `axis=1`: stolpci ($n$ stolpcev),
* **$3$-dimenzionalni `array`** oblike $(k, m, n)$:
  - `axis=0`: plasti/globina ($k$ plasti),
  - `axis=1`: vrstice ($m$ vrstic),
  - `axis=2`: stolpci ($n$ stolpcev).

### Iskanje elementov
* `np.flatnonzero(x)` vrne indekse neničelnih elementov.
* `np.where(condition)` vrne indekse, kjer je `condition == True`.
  - **Vektor**: `(array([indeksi]),)`,
  - **Matrika**: `(array([vrstice]), array([stolpci]))`,
  - **$N$-dimenzionalni `array`**: $N$-terica (vsaka za eno dimenzijo)
* `np.where(condition, t, f)` vrne `ndarray`, kjer izbere `t` če `True`, sicer `f`.

### Kumulativne operacije
* `np.cumsum(x, axis=None)` izračuna kumulativno vsoto vzdolž izbrane osi.