In [131]:
import numpy as np

# Mafijski piknik

Mafijski piknik je letno srečanje študentov in zaposlenih na FMF. Poleg žara in športnih aktivnosti se seveda prileže tudi pivo, ki se hrani v velikih sodih. Ker se dan po pikniku vsi sprašujejo kam so izginile enormne količine piva, so se organizatorji letos odločili, da na sode namestijo merilnike, ki merijo višino gladine piva. Poln sod ima gladino na višini 0, tako da morajo biti smiselni izmerki manjši ali enaki nič. Pomagaj organizatorjem napisati program, ki obdeluje podatke dobljene z merilnikom.

Pri tej nalogi je uporaba zank prepovedana. Če uporabljate zanke, lahko dosežete največ tretjino možnih točk.

Minister za zdravje opozarja: Prekomerno pitje alkohola škoduje zdravju!

## 1. naloga

Merilnik proizvajalca A zajema meritve v enakomernih časovnih razmikih `Δt`, prva meritev je ob času `Δt`.

Napiši program `povprecni_pretok_a(x, S, delta_t)`, ki za zaporedne meritve višine gladine soda s presekom `S` shranjene v `1D` tabeli (`np.ndarray`) `x` izračuna povprečen pretok v času do začetka vsake meritve ter rezultate vrne v `1D` tabeli. Povprečen pretok je enak celotnemu pretočenemu volumnu deljenemu s celotnim pretečenim časom.

Primer:

`povprecni_pretok_a(np.array([0, -1.2, -2.5, -6, -12]), 1, 0.5)` vrne `array([0., -1.2, -1.66666667, -3., -4.8])`

In [132]:
x, S, delta_t = np.array([0, -1.2, -2.5, -6, -12]), 1, 0.5

Zmanjšanje volumna ob času $t_i$ je $V_i = S \cdot x$. Povprečni odtok pa je $\frac{V_i}{t_i}$

In [133]:
# Mnozimo s skalarjem
V = S * x

In [134]:
# Ustvarimo tabelo t_i-jev, ki so enakomerno razporejeni od delta_t naprej
t = np.arange(delta_t, delta_t * (len(x) + 1), delta_t)

In [135]:
# Mnnomzimo po komponentah
V / t

array([ 0.        , -1.2       , -1.66666667, -3.        , -4.8       ])

In [136]:
np.arange(delta_t, delta_t * (len(x) + 1))

array([0.5, 1.5, 2.5])

## 2. naloga

Merilnik proizvajalca B meritve zajema ob poljubnih časih, časovni interval med `(i - 1)`-to in `i`-to meritvijo podamo v `1D` tabeli `delta_t` na mestu `i`. So pa nekatere meritve tega merilnika napačne, in sicer pokažejo višino, ki je večja od `0`.

Te meritve izloči iz podatkov in jih ne uporabi v obdelavi. Napiši funkcijo `povprecni_pretok_b(x, S, delta_t)`, ki naredi enako kot prejšnja funkcija, le za merilnik proizvajalca B. Predpostaviš lahko, da je vsaj ena meritev veljavna.

Namig: Za izračun časa (kumulativnih vsot) utegne koristiti ena izmed standardnih numpy funkcij - `np.cumsum(x)`

Primer:

`povprecni_pretok_b(np.array([0, -1.2, 3, -2.5, -6, -12]), 1, np.array([0.5, 1., 0.1, 0.5, 1., 0.2]))` vrne `array([0., -0.8, -1.19047619, -1.93548387, -3.63636364])`.

Komentar: V tem primeru meritve potekajo ob časih `[0.5, 1.5, 1.6, 2.1, 3.1, 3.3]`.

In [137]:
x, S, delta_t = np.array([0, -1.2, 3, -2.5, -6, -12]), 1, np.array([0.5, 1., 0.1, 0.5, 1., 0.2])

In [138]:
# Kako dobimo samo veljavne meritve?
print(x)
# To nam poda vektor True/False
veljavna_mesta = x <= 0

[  0.   -1.2   3.   -2.5  -6.  -12. ]


In [139]:
# Mnozenje True/False vektorja z vektorjem
veljavni_x = x[veljavna_mesta]
V = S * veljavni_x

In [140]:
# Kako dobimo t?
t = np.cumsum(delta_t)
# Ampak ta vsebuje vse case, mi pa rabimo samo veljavne, da bomo lahko mnozili po komponentah
veljavni_t = t[veljavna_mesta]

In [141]:
# Ostane le da vrnemo rezultat
V / veljavni_t

array([ 0.        , -0.8       , -1.19047619, -1.93548387, -3.63636364])

## 3. naloga

Po nekaj vrčkih piva so se študentje spomnili veliko zabavnejše uporabe nakupljenih senzorjev. Odločili so se, da bodo izmerili kako hitro (oziroma s kolikšnim največjim pretokom) lahko človek pije pivo. Vsakemu udeležencu eksperimenta so priredili sod z merilnikom proizvajalca A. Meritve za `i`-tega udeleženca shranimo v `2D` tabelo podatki v `i`-to vrstico. Prav tako so določili, da je največji teoretični pretok skozi človeško grlo enak `phi_max` (`phi_max < 0`), torej vsi udeleženci, ki so ob katerem koli času pili s povprečnim pretokom po absolutni vrednosti večjim (zaradi negativnega znaka to pomeni manjšim) od `phi_max`, so goljufali.

Napiši funkcijo `najhitrejsi_pivec(podatki, S, delta_t, phi_max)`, ki vrne par (`tuple`), v katerem je na prvem mestu po absolutni vrednosti največji (ker so vsi smiselni pretoki negativni, to pomeni najmanjši) izmerjen povprečni pretok ob poljubnem času, pri čemer dosežki goljufivcev niso upoštevani, in na drugem mestu seznam (`list`) zaporednih števil udeležencev, ki so goljufali. Predpostaviš lahko, da vsaj en udeleženec ni goljufal.

Primer:

`najhitrejsi_pivec(np.array([[0, -1.2, -2.5, -6, -12], [0, -0.6, -2, -3, -4.1], [0, -0.7, -2.3, -5.5, -8]]), 1, 0.5, -4.)` vrne (-3.2, [0])

In [142]:
podatki, S, delta_t, phi_max = np.array([[0, -1.2, -2.5, -6, -12], [0, -0.6, -2, -3, -4.1], [0, -0.7, -2.3, -5.5, -8]]), 1, 0.5, -4.

In [143]:
# Vidimo, da imamo 3 pivce, saj imamo 3 vrstice.
print(podatki)
st_vrstic = podatki.shape[0]
st_stolpcev = podatki.shape[1]

[[  0.   -1.2  -2.5  -6.  -12. ]
 [  0.   -0.6  -2.   -3.   -4.1]
 [  0.   -0.7  -2.3  -5.5  -8. ]]


In [144]:
# Najprej naredimo vektor casov, kot pri prvi nalogi
t = np.arange(delta_t, delta_t * (st_stolpcev + 1), delta_t)

In [145]:
# Izracunajmo sedaj za vse naekrat njihov pretok phi:
# Mnozenje s sklarajem
V = S * podatki
# Mnozenje po elementih po vrsticah
phi = V / t

In [146]:
# Poiscimo za vsakega tekmovalca najbolsi pretok - minimum po vrsticah
najbolsi_phi = np.min(phi, axis = 1)

In [147]:
# Poiscimo zmagovalca oz. vrednost med negoljufi
negoljufi = phi[najbolsi_phi >= phi_max]
zmagovalna_vrednost = np.min(negoljufi)

In [148]:
# Potrebujemo goljufe v obliki seznama in indeksa goljufa
goljufi_tf = najbolsi_phi < phi_max
# Potrebujemo goljufe v obliki seznama in indeksa
goljufi = np.flatnonzero(goljufi_tf)

# Klada na klancu

Pri tej nalogi je uporaba zank prepovedana. Če uporabljate zanke, lahko dosežete največ tretjino možnih točk.

Pri praktikumu merimo hitrost klade, ki drsi po klancu. Izvedli smo $N$ ponovitev eksperimenta pri katerih smo z ultrazvočnim senzorjem razdalje merili položaj klade vzdolž klanca v odvisnosti od časa.

Ultrazvočni merilnik deluje preko odboja zvoka. Najprej z majhnim zvočnikom generira kratek ultrazvočni pulz, nato pa ga z vgrajenim mikrofonom zazna. Čas med poslanim paketom in zaznanim odbojem nam ta senzor vrne v enotah $ms$
. Izmerjeni časi se nahajajo v `2D` tabeli (`np.ndarray`) oblike $(N,N_t)$, kjer je $N$ število ponovitev eksperimenta, $N_t$ pa število meritev razdalje med potekom vsakega eksperimenta. Prvo meritev položaja opravimo vedno pri času $t=0$, vse ostale pa pri časih, ki so za $dt=0.01$ s večji od prejšnjega časa.

## 1. naloga

Če želimo čas potovanja sunka pretvoriti v razdaljo moramo rešiti preprosto enačbo $s=\frac{1}{2} c_{air} t$, kjer je $s$ razdalja od klade do senzorja, $c_{air}$ hitrost zvoka v zraku in $t$ čas potreben za odboj. Na žalost je hitrost zvoka v zraku odvisna od temperature, zato moramo upoštevati tudi to. Privzemi, da se hitrost zvoka v zraku (izražena v $\frac{m}{s}$) izračuna kot $c_{air}=\sqrt{401.88T}$; kjer je $T$ temperatura izražena v Kelvinih. Ob vsaki ponovitvi eksperimenta si v `1D` tabelo `temperatura` zapišemo temperaturo zraka v kelvinih.

Sestavi funkcijo `pretvori_v_razdaljo(casi, temperatura)`, ki nam čase med poslanim pulzom (merjeno v $\frac{m}{s}) in njegovo zaznavo pretvori v razdaljo izraženo v metrih.

Primer za eno ponovitev eksperimenta ($N=1$) in dve ponovitvi:

`pretvori_v_razdaljo(np.array([[10.1, 5.25, 0.4]]), np.array([294.30523903]))` vrne `array([[1.73675505 0.90276872 0.06878238]])`

`pretvori_v_razdaljo(np.array([[10.1, 0.4],[10.0713254, 0.37488064]]), np.array([295.39220127, 296.57263143]))` vrne `array([[1.73995929, 0.06890928], [1.73848267, 0.0647108]])`

In [149]:
casi, temperatura = np.array([[10.1, 0.4],[10.0713254, 0.37488064]]), np.array([295.39220127, 296.57263143])

In [150]:
# Izracunati moramo formulo, zacnimo z c_air
c = np.sqrt(401.88 * temperatura)
# Da se bo vsaka temperatura prilegala vsaki vrstici v casi moramo temperatura spremeniti v obliko (N,1)
c = c.reshape(len(temperatura), 1)

In [151]:
# Zmnozimo ostalo in upostevamo pretvorba iz milisekund v sekunde
resitev = 0.5 * c * (casi * 1e-3)

# 2. naloga

Sedaj bi iz dobljenih položajev klade radi izračunali hitrosti. Sestavi funkcijo `povprecne_hitrosti(polozaji)`, ki sprejme prej izračunane položaje oblike $(N,N_t)$ vrne pa tabelo, ki na prvem mestu vsake vrstice vsebuje povprečno hitrost ponovitve, na nadaljnjih mestih pa izračunane trenutne hitrosti med eksperimenti v enotah $\frac{m}{s}$. Časi med posameznimi meritvami položaja so konstantni in znašajo $0.01 s$. Izhodna tabela bo torej oblike $(N,N_t)$ ($N_t−1$ trenutnih hitrosti $+1$ za povprečno hitrost).

Primer:

`povprecne_hitrosti(np.array([[1.71962294, 0.06810388], [1.75406856, 0.06371724]]))` vrne `array([[-165.151906, -165.151906], [-169.035132, -169.035132]])` 

`povprecne_hitrosti(np.array([[1.70044888, 0.88389669, 0.06734451]]))` vrne `array([[-81.6552185, -81.655219 , -81.655218 ]])`

In [152]:
polozaji = np.array([[1.71962294, 0.06810388], [1.75406856, 0.06371724]])

Če je polozajipolozaji matrika oblik $(N, N_t)$, potem ima vsaka vrstica zaporedne položaje klade: $[p_0,  p_1,  p_2, \ldots,  p_{N_t−1}]$.

Trenutna hitrost (med dvema zaporednima točkama) za časovni preskok $\Delta t$ izračunamo kot $v_i  =  \frac{p_{i+1}−p_i}{\Delta t}$.

Ker imamo N_t​ položajev, dobimo N_{t−1} takšnih trenutnih hitrosti na vsako vrstico.

Nato izračunamo povprečno hitrsot kot artimetično sredino

In [153]:
# Trenutna hitrost je 
# polozaji[:, 1:] je podmatrika, ki vzame vse vrstice, stolpce od 1 naprej
# polozaji[:, :-1] vzame vse vrstice, stolpce od začetka do enega pred koncem
vs = (polozaji[:, 1:] - polozaji[:, :-1]) / 0.01

In [154]:
# Izracunamo povprecje po vrsticah
vs_avg = np.average(vs, axis=1)
# In preoblikujemo v stolpicni vektor
vs_avg = vs_avg.reshape(len(vs_avg), 1)

In [155]:
# Prilepimo povprečno hitrost kot prvi stolpec pred trenutne hitrosti
np.concatenate((vs_avg, vs), axis=1)

array([[-165.151906, -165.151906],
       [-169.035132, -169.035132]])

## 3. naloga

Pri obdelavi podatkov opaziš, da imajo nekateri eksperimenti veliko večjo razpršenost rezutatov kot drugi - razpršenost merimo s standarno deviacijo, ki jo za določen eksperiment izracunamo kot $\sqrt{\frac{1}{N} \sum_i (v_i - v_{avg})^2}$. Zaveš se, da obstaja možnost, da si med pripravo posameznih ponovitev eksperimenta po pomoti pritisnil na gumb, ki preklaplja med visoko in nizko časovno ločljivostjo senzorja. Pokvarjene ponovitve si se odločil odstraniti iz seta meritev, tako da jih ne boš upošteval.

Sestavi funkcijo `koncno_povprecje(polozaji, meja_std)`, ki sprejme položaje klade za vse ponovitve eksperimenta ter mejo standardne deviacije. Funkcija naj izračuna standardno deviacijo hitrosti za vsako ponovitev, ter izloči vse eksperimente, kjer ta vrednost znaša več kot določena meja. Na preostalih eksperimentalnih ponovitvah naj nato izračuna in vrne povprečno hitrost povrečnih hitrosti zaokroženo na $2$ decimalki.

Namig: Za zaokroževanje uporabi funkcijo round.

Primer:

`koncno_povprecje(np.array([[1.70902097, 0.88835248, 0.067684], [1.7191911, 0.89788999, 0.07649603]]), 0.5)` vrne `-82.10`

In [158]:
# Resitev 2. naloge
def povprecne_hitrosti(polozaji):
    vs = (polozaji[:, 1:] - polozaji[:, :-1]) / 0.01
    vs_avg = np.atleast_2d(np.average(vs, axis=1))
    return np.concatenate((vs_avg.T, vs), axis=1)

In [156]:
# 1) Za vsako vrstico polozaji (tj. za vsak eksperiment) izračunamo:
#    - povprečno hitrost (prvi stolpec) in
#    - trenutne hitrosti (naslednji stolpci).
povp = povprecne_hitrosti(polozaji)

NameError: name 'povprecne_hitrosti' is not defined

In [ ]:
# povp[:, 0]  -> vektor povprečnih hitrosti vsakega eksperimenta (dolžine N)
vs_avg = povp[:, 0]
# povp[:, 1:] -> matrika trenutnih hitrosti (oblika N x (Nt-1))
vs = povp[:, 1:]

In [ ]:
# 2) Izračun standardne deviacije hitrosti za vsako vrstico (vsak eksperiment).
#    Formula za standardno deviacijo eksperimenta i:
#
#       sigma_i = sqrt( (1/(Nt-1)) * ∑ (v_k - v_avg)^2 ),   k = 1..(Nt-1)
#
#    pri čemer so v_k trenutne hitrosti v eksperimentu i, v_avg je povprečna hitrost v eksperimentu i.
#    (len(polozaji[0]) - 1) = (Nt - 1), ker polozaji[0] je ena vrstica = Nt meritev.
#
#    Postopek:
#    - vs.T - vs_avg  odšteje vsaki vrstici njeno povprečno hitrost,
#      pri čemer NumPy "razširi" (broadcasta) vs_avg ustrezno po stolpcih.
#    - np.square(...) kvadrira razlike.
#    - ... .T preoblikuje nazaj, da vsako vrstico seštejemo po stolpcih (axis=1).
#    - pomnožimo z 1/(Nt-1) in vzamemo koren (sqrt).
sigmas = np.sqrt(
    (1 / (len(polozaji[0]) - 1)) * 
    np.sum(np.square(vs.T - vs_avg).T, axis=1)
)

In [ ]:
# 3) Izločimo vse eksperimente, ki imajo standardno deviacijo večjo od mejne (meja_std).
#    np.where(sigmas < meja_std) vrne indekse eksperimentov (vrstic), ki ustrezajo pogoju.
#    vs[np.where(sigmas < meja_std)] pobere vse hitrosti iz tistih vrstic.

# 4) Na preostalih hitrostih (združenih v eno vektorsko polje) izračunamo povprečje (np.average)
#    in ga zaokrožimo na 2 decimalki (round(..., 2)).
round(np.average(vs[np.where(sigmas < meja_std)]), 2)