# Nekaj uporabnih funkcij v Numpy

In [38]:
import numpy as np

* `np.linspace(start, stop, num)` vrne `narray` `num` enakomerno razporejenih vrednosti znotraj intervala `start`, `stop`.

In [39]:
x = np.linspace(0, 1, 6)

print(x)

[0.  0.2 0.4 0.6 0.8 1. ]


* `np.roll(x, shift)` premakne elemente v vektorju `x` za `shift` mest. . Če je `shift` pozitivno število, se premik izvede v desno, če je negativno, se premik izvede v levo.

In [40]:
np.roll(x,1)

array([1. , 0. , 0.2, 0.4, 0.6, 0.8])

In [41]:
np.roll(x, -1)

array([0.2, 0.4, 0.6, 0.8, 1. , 0. ])

* `np.reshape(x, newshape)` vrne vrednosti v `x` v novi obliki, ki jo specificira `newshape`.

In [42]:
np.reshape(x, (2,3))

array([[0. , 0.2, 0.4],
       [0.6, 0.8, 1. ]])

* `np.flatnonzero(x)` vrne indekse vse neničenlih vrednosti `x`.

In [43]:
x = np.array([0, 1, 2, 0, 3])
np.flatnonzero(x)

array([1, 2, 4], dtype=int64)

In [44]:
matrika = np.array([[0, 1, 0],
                    [0, 0, 3],
                    [4, 0, 0]])
np.flatnonzero(matrika)

array([1, 5, 6], dtype=int64)

* `np.where(x, t, f)`, kjer `x` vsebuje samo vrednosti `False` in `True`. Parametra `t` in `f` sta neobvezna. Če ju ne podamo, vrne indekse elementov `True`. Če podamo `t` in `f`, ustvari nov vektor, in na mestih kjer je vrednost `True` vrne `t` in kjer je `False` `f`.  

In [45]:
x = np.array([0, 1, 2, 0, 3, 4])
np.where(x > 1)

(array([2, 4, 5], dtype=int64),)

In [46]:
x = np.array([0, 1, 2, 3, 4])
np.where(x % 2 == 0, "sodo", "liho")

array(['sodo', 'liho', 'sodo', 'liho', 'sodo'], dtype='<U4')

* `np.cumsum(x, axis=None)` izračuna kumultivno vsoto vzdolž dane osi `axis` (oz. nad celotnim `x`, če `axis` ni podana). Kumultivna vsota vsakega elementa je vsota vseh prejšnjih elementov v nizu do tega elementa (vključno z njim).

In [47]:
x = np.array([1, 2, 3, 4])
np.cumsum(x)

array([ 1,  3,  6, 10])

In [48]:
matrika = np.array([[1, 2, 3],
                    [4, 5, 6]])

In [49]:
# Kumultivna vsota vzdolž vrstic (axis=1)
np.cumsum(matrika, axis=1)

array([[ 1,  3,  6],
       [ 4,  9, 15]])

In [50]:
# Kumultivna vsota vzdolž stolpcev (axis=0)
np.cumsum(matrika, axis=0)

array([[1, 2, 3],
       [5, 7, 9]])

In [51]:
# Kumultivna vsota celotnega niza (axis=None)
np.cumsum(matrika)

array([ 1,  3,  6, 10, 15, 21])